// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/image-crop/CropDialog.tsx": () => import("../components/mockups/image-crop/CropDialog.tsx"),
  "./components/mockups/scoreboard/Current.tsx": () => import("../components/mockups/scoreboard/Current.tsx")
};
